name: 'UE5-Build-Project'
description: 'Cook, stage, and package projects for Unreal Engine'
author: 'Orchid Isle Games'
branding:
  icon: 'anchor'
  color: 'green'

inputs:
  RUNUAT_PATH:
    description: 'Path to RunUAT.bat'
    required: true
  UPROJECT_PATH:
    description: 'Path to the .uproject file'
    required: true
  BUILD_CONFIG:
    description: 'Configuration to use'
    required: true
    default: 'Development'
  PLATFORM:
    description: 'Platform to build for'
    required: true
  COOK:
    description: 'Whether to cook'
    required: false
    default: 'true'
  STAGE:
    description: 'Whether to stage'
    required: false
    default: 'true'
  PACKAGE:
    description: 'Whether to package'
    required: false
    default: 'false'
  PAK:
    description: 'Whether to pak files'
    required: false
    default: 'false'
  SERVER:
    description: 'Whether to include the server'
    required: false
    default: 'false'
  ARCHIVE:
    description: 'Whether to archive'
    required: false
    default: 'false'
  ARCHIVE_PATH:
    description: 'Archive Path'
    required: false
  EDITOR:
    description: 'Whether to compile the editor as well'
    required: false
    default: 'true'
  ENCRYPT_INI:
    description: 'Encrypt INI Files'
    required: false
    default: 'false'
  RELEASE:
    description: 'Create Release Version (Enter new release version number)'
    required: false
    default: 'false'
  PATCH:
    description: 'Generate a patch based on a release version (enter based on release version number)'
    required: false
    default: 'false'
  MAPS:
    description: 'Maps to build and package (comma separated list of maps)'
    required: false
  
runs:
  using: 'composite'
  steps:
    - shell: powershell
      run: |
        $runUatPath = "${{ inputs.RUNUAT_PATH }}"
        $uprojectPath = "${{ inputs.UPROJECT_PATH }}"
        $buildConfig = "${{ inputs.BUILD_CONFIG }}"
        $platform = "${{ inputs.PLATFORM }}"
        $server = "${{ inputs.SERVER }}"
        $cook = "${{ inputs.COOK }}"
        $stage = "${{ inputs.STAGE }}"
        $pak = "${{ inputs.PAK }}"
        $package = "${{ inputs.PACKAGE }}"
        $archive = "${{ inputs.ARCHIVE }}"
        $archivePath = "${{ inputs.ARCHIVE_PATH }}"
        $editor = "${{ inputs.EDITOR }}"
        $encryptIni = "${{ inputs.ENCRYPT_INI }}"
        $release = "${{ inputs.RELEASE }}"
        $patch = "${{ inputs.PATCH }}"
        $maps = "${{ inputs.MAPS }}"
  
        $serverArg = if ($server -eq 'true') { "-server -serverplatform=$platform -noclient" } else { "" }
        $cookArg = if ($cook -eq 'true') { "-cook" } else { "" }
        $stageArg = if ($stage -eq 'true') { "-stage" } else { "" }
        $pakArg = if ($pak -eq 'true') { "-pak" } else { "" }
        $packageArg = if ($package -eq 'true') { "-package" } else { "" }
        $archiveArg = if ($archive -eq 'true') { "-archive -archivedirectory=$archivePath" } else { "" }
        $editorArg = if ($archive -eq 'true') { "-nocompileeditor" } else { "" }
        $encryptIniArg = if ($encryptIni -eq 'true') { "-encryptinifiles" } else { "" }
        $releaseArg = if ($release -ne 'false') { "-createreleaseversion=$release" } else { "" }
        $patchArg = if ($patch -ne 'false') { "-generatepatch -basedonreleaseversion=$patch" } else { "" }
  
        $command = "& `"$runUatPath`" BuildCookRun " +
                  "-project=`"$uprojectPath`" " +
                  "-clientconfig=$buildConfig -serverconfig=$buildConfig -platform=$platform -map=$maps " +
                  "$serverArg $cookArg $stageArg $pakArg $packageArg $archiveArg $editorArg $encryptIniArg $releaseArg $patchArg " +
                  "-noP4 -build -unattended -utf8output -prereqs"
        
        Invoke-Expression $command
